name: anntraining
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - conda-forge
dependencies:
  #basics
  - python=3.7
  #jupyter
  - ipykernel
  - jupyter_client
  - jupyter
  # dev
  - autopep8
  # scientific core
  - pandas
  # windows io
  - xlrd >= 1.0.0
  - openpyxl # xls 
  # custom
  - pyhecdss
  # machine learning
  - statsmodels
  - tensorflow #=2.1
  - keras
  - keras-tuner
  - scikit-learn
  # vizualization
  - bokeh
  - hvplot
  - holoviews
  - panel
